const flows={
 none:{title:'Интернета нет совсем',steps:[
  {title:'Пропал ли интернет на всех устройствах?',text:'Откройте знакомый сайт на телефоне и компьютере. Если проблема только на одном устройстве, выберите соответствующий пункт ниже.',yes:'Не работает нигде',no:'Только на одном устройстве',next:1,route:'device'},
  {title:'Посмотрите на индикаторы',text:'Power обычно горит постоянно. Если LOS горит красным или мигает, возможно, нужна проверка линии. Кабели не трогайте.',yes:'Индикаторы выглядят обычно',no:'Красный LOS или всё погасло',next:2},
  {title:'Перезапустите роутер',text:'Отключите питание от розетки на 30 секунд и подключите снова. Не нажимайте Reset. Подождите до 3 минут.',yes:'Интернет появился',no:'Не появился',next:3},
  {title:'Обратитесь в поддержку',text:'Если LOS красный или перезапуск не помог, сообщите оператору, какие индикаторы горят и что вы уже проверили.',end:true}
 ]},
 slow:{title:'Интернет медленный',steps:[
  {title:'Проверьте другое устройство',text:'Поставьте на паузу большие загрузки и проверьте интернет на другом устройстве.',yes:'На другом работает нормально',no:'Медленно на всех устройствах',next:1},
  {title:'Подойдите ближе к роутеру',text:'Если рядом скорость лучше, сигналу могут мешать стены или расположение оборудования. Поставьте роутер открыто, повыше и ближе к центру дома.',yes:'Рядом стало быстрее',no:'Даже рядом медленно',next:2},
  {title:'Перезапустите роутер',text:'Отключите питание на 30 секунд, включите и подождите до 3 минут. Повторите проверку.',yes:'Стало лучше',no:'По-прежнему медленно',next:3},
  {title:'Попросите проверить подключение',text:'Если проблема есть на всех устройствах рядом с роутером, обратитесь в поддержку оператора. Уточните, когда началось замедление.',end:true}
 ]},
 wifi:{title:'Wi‑Fi пропадает или плохо ловит',steps:[
  {title:'Сравните связь рядом с роутером',text:'Проверьте интернет в проблемной комнате и рядом с роутером. Если рядом стабильно, сигналу могут мешать стены или расстояние.',yes:'Рядом стабильно',no:'Пропадает и рядом',next:1},
  {title:'Переставьте роутер',text:'Выберите открытое место повыше. Не прячьте роутер в шкаф и не ставьте за телевизор или металлические предметы.',yes:'Сигнал стал лучше',no:'Всё ещё слабый',next:2},
  {title:'Перезапустите роутер',text:'Отключите питание на 30 секунд и включите снова. Подождите до 3 минут. Проверьте, не закрыты ли вентиляционные отверстия.',yes:'Связь стабильна',no:'Wi‑Fi пропадает',next:3},
  {title:'Обратитесь в поддержку',text:'Если Wi‑Fi пропадает даже рядом после перезапуска, оператор поможет проверить подключение. Не меняйте незнакомые настройки роутера.',end:true}
 ]},
 device:{title:'Не подключается одно устройство',steps:[
  {title:'Проверьте настройки Wi‑Fi',text:'Убедитесь, что Wi‑Fi включён, а режим «В самолёте» выключен. Проверьте, видна ли домашняя сеть.',yes:'Сеть видна',no:'Сеть не отображается',next:1},
  {title:'Подключитесь заново',text:'На устройстве выберите сеть, нажмите «Забыть», затем подключитесь снова с паролем роутера. Не отправляйте пароль другим людям.',yes:'Подключилось',no:'Не удалось',next:2},
  {title:'Перезапустите устройство',text:'Выключите и включите Wi‑Fi или перезагрузите устройство. Попробуйте подключиться рядом с роутером.',yes:'Теперь работает',no:'Всё ещё не работает',next:3},
  {title:'Попросите помочь с устройством',text:'Если другие устройства подключаются, обратитесь к производителю устройства или в поддержку оператора. Не сбрасывайте роутер.',end:true}
 ]}
};
let activeCase='',activeStep=0;const panel=document.getElementById('flowPanel');
function drawFlow(){const flow=flows[activeCase],s=flow.steps[activeStep];panel.hidden=false;panel.innerHTML=`<div class="flow-top"><span>ШАГ ${activeStep+1} ИЗ ${flow.steps.length} · ${flow.title.toUpperCase()}</span><button id="closeFlow">Закрыть ×</button></div><h3>${s.title}</h3><p>${s.text}</p>${s.end?'':`<div class="flow-actions"><button class="yes" id="answerYes">${s.yes}</button><button id="answerNo">${s.no}</button></div>`}<div class="step-line"><i style="width:${((activeStep+1)/flow.steps.length)*100}%"></i></div>`;document.getElementById('closeFlow').onclick=()=>{panel.hidden=true;document.querySelectorAll('.symptom-card').forEach(x=>x.classList.remove('active'))};if(!s.end){document.getElementById('answerYes').onclick=()=>{if(s.route==='device'){activeCase='device';activeStep=0}else activeStep=s.next;drawFlow()};document.getElementById('answerNo').onclick=()=>{activeStep=s.next;drawFlow()}}panel.scrollIntoView({behavior:'smooth',block:'nearest'})}
document.querySelectorAll('.symptom-card').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.symptom-card').forEach(x=>x.classList.remove('active'));card.classList.add('active');activeCase=card.dataset.case;activeStep=0;drawFlow()}));
const modelInput=document.getElementById('modelInput'),guideResults=document.getElementById('guideResults');
function findGuide(){const model=modelInput.value.trim();if(!model){modelInput.focus();modelInput.setCustomValidity('Введите марку и модель устройства');modelInput.reportValidity();return}modelInput.setCustomValidity('');const isStb=/пристав|set.?top|stb|eltex|nv\s?\d|tv\+|тв/i.test(model),query=`${model} ${isStb?'настройка инструкция':'ADSL настройка'} ${isStb?'ТВ приставка':'видео инструкция'}`,yt='https://www.youtube.com/results?search_query='+encodeURIComponent(query),web='https://www.google.com/search?q='+encodeURIComponent(query),safeModel=model.replace(/[^a-z0-9-]/gi,'').toLowerCase(),tp='https://www.tp-link.com/kz/support/download/'+safeModel+'/',isTp=/tp.?link|archer|td-w/i.test(model),isW8961=/td.?w8961n/i.test(model);guideResults.innerHTML=`<div class="results-heading">Инструкции для <b>${escapeHtml(model)}</b></div><div class="result-links">${isW8961?`<a class="result-link video" href="https://www.youtube.com/watch?v=z_Mu8EGdDZA" target="_blank" rel="noopener noreferrer"><span class="result-icon">▶</span><span><b>Видео от TP-Link Kazakhstan: TD-W8961N</b><small>Настройка ADSL-модема · Казахтелеком</small></span><span class="result-arrow">↗</span></a>`:''}<a class="result-link video" href="${yt}" target="_blank" rel="noopener noreferrer"><span class="result-icon">▶</span><span><b>Найти видеоинструкции по этой модели</b><small>YouTube · поиск по точному названию</small></span><span class="result-arrow">↗</span></a><a class="result-link" href="${web}" target="_blank" rel="noopener noreferrer"><span class="result-icon doc">⌕</span><span><b>Другие видео и текстовые инструкции</b><small>Поиск в интернете по марке и модели</small></span><span class="result-arrow">↗</span></a>${isTp?`<a class="result-link" href="${tp}" target="_blank" rel="noopener noreferrer"><span class="result-icon doc">▤</span><span><b>Страница поддержки TP-Link</b><small>Руководства и загрузки · проверьте аппаратную версию</small></span><span class="result-arrow">↗</span></a><a class="result-link" href="https://www.tp-link.com/nl/support/faq/3839/" target="_blank" rel="noopener noreferrer"><span class="result-icon doc">▤</span><span><b>Официальное руководство по настройке DSL</b><small>TP-Link · общие шаги для ADSL/VDSL</small></span><span class="result-arrow">↗</span></a>`:''}</div>`;guideResults.scrollIntoView({behavior:'smooth',block:'nearest'})}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}document.getElementById('findGuide').onclick=findGuide;modelInput.addEventListener('keydown',e=>{if(e.key==='Enter')findGuide()});
const lessons=[['Найдите удачное место','Поставьте роутер открыто, повыше и ближе к центру жилья. Стены, шкафы и крупная техника могут ослаблять Wi‑Fi.','Не закрывайте вентиляционные отверстия.'],['Подключите устройства','Откройте настройки Wi‑Fi, выберите имя сети с наклейки роутера и введите пароль.','Имя сети и пароль обычно указаны на корпусе роутера.'],['Посмотрите на индикаторы','Power означает питание. Wi‑Fi показывает беспроводную сеть. PON и LOS относятся к оптической линии.','Значение индикаторов зависит от модели оборудования.'],['Что делать при сбое','Проверьте интернет на нескольких устройствах, посмотрите на индикаторы и один раз перезапустите питание.','Не используйте Reset без инструкции специалиста.']];let lessonIndex=0;
function renderLesson(){const l=lessons[lessonIndex];document.getElementById('lessonCount').textContent=`0${lessonIndex+1} / 04`;document.getElementById('lessonProgress').style.width=`${(lessonIndex+1)*25}%`;document.getElementById('lessonContent').innerHTML=`<span class="lesson-kicker">УРОК 0${lessonIndex+1}</span><h3>${l[0]}</h3><p>${l[1]}</p><span class="lesson-tip">${l[2]}</span>`;document.getElementById('lessonDots').innerHTML=lessons.map((_,i)=>`<button class="${i===lessonIndex?'active':''}" aria-label="Урок ${i+1}" data-index="${i}"></button>`).join('');document.querySelectorAll('#lessonDots button').forEach(b=>b.onclick=()=>{lessonIndex=+b.dataset.index;renderLesson()})}
document.getElementById('prevLesson').onclick=()=>{lessonIndex=(lessonIndex+3)%4;renderLesson()};document.getElementById('nextLesson').onclick=()=>{lessonIndex=(lessonIndex+1)%4;renderLesson()};renderLesson();
const terms=[['Роутер','Устройство, которое раздаёт интернет по Wi‑Fi и кабелю внутри дома.'],['Wi‑Fi','Беспроводное соединение между роутером и устройствами.'],['Оптика','Тонкий кабель для передачи данных световыми сигналами. Не сгибайте и не отсоединяйте его.'],['PON','На многих оптических устройствах показывает состояние соединения с сетью.'],['LOS','Индикатор потери оптического сигнала. Красный или мигающий свет может означать неполадку.'],['Задержка','Время прохождения данных до сервера и обратно. Важна для звонков и онлайн-игр.'],['Перезагрузка','Отключение питания на короткое время. Сохранённые настройки остаются.'],['Reset','Сброс к заводским настройкам. Не нажимайте без инструкции специалиста.']];document.getElementById('termList').innerHTML=terms.map(t=>`<button class="term"><span>+</span>${t[0]}<div class="term-detail">${t[1]}</div></button>`).join('');document.querySelectorAll('.term').forEach(t=>t.onclick=()=>{t.classList.toggle('open');t.querySelector('span').textContent=t.classList.contains('open')?'−':'+'});
const toast=document.getElementById('toast');function showToast(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}document.getElementById('shareBtn').onclick=async()=>{const data={title:'Связь рядом — помощь с интернетом',text:'Понятная памятка: как разобраться с домашним интернетом',url:location.href};try{if(navigator.share)await navigator.share(data);else if(navigator.clipboard){await navigator.clipboard.writeText(location.href);showToast('Ссылка скопирована — можно отправить абоненту')}else showToast('Скопируйте адрес страницы из браузера')}catch(e){if(e.name!=='AbortError')showToast('Скопируйте адрес страницы из браузера')}};
